name: Dev CI (Build & Pack)

on:
  push:
    branches:
      - dev

concurrency:
  group: dev-ci
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  dev-ci:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      PROJECT: src/Space.Modules.InMemoryCache/Space.Modules.InMemoryCache.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/global.json

      - name: Restore
        run: dotnet restore "$PROJECT"

      - name: Build (Release)
        run: dotnet build "$PROJECT" -c Release -p:ContinuousIntegrationBuild=true --no-restore

      - name: Pack
        run: |
          mkdir -p artifacts
          VERSION="0.0.0-dev.${GITHUB_RUN_NUMBER}+sha.$(git rev-parse --short HEAD)"
          echo "Packing $PROJECT -> ${VERSION}";
          dotnet pack "$PROJECT" -c Release -p:PackageVersion=${VERSION} -p:ContinuousIntegrationBuild=true -o artifacts --no-build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dev-artifacts
          path: artifacts/*.nupkg
          retention-days: 7
