name: Release Publish

on:
  release:
    types: [published]

concurrency:
  group: release-publish
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      PROJECT: src/Space.Modules.InMemoryCache/Space.Modules.InMemoryCache.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/global.json

      - name: Resolve Version From Release
        id: version
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          echo "Release tag: $TAG"
          if [[ ! $TAG =~ ^[vV][0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release tag must be vX.Y.Z" >&2
            exit 1
          fi
          BASE=${TAG#v}; BASE=${BASE#V}
          VERSION="$BASE"
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            VERSION+="-preview"
          fi
          echo "Resolved version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "### Version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Restore
        run: dotnet restore "$PROJECT"

      - name: Build (Release)
        run: dotnet build "$PROJECT" -c Release --no-restore -p:Version=${VERSION} -p:ContinuousIntegrationBuild=true

      - name: Pack
        run: |
          mkdir -p artifacts
          echo "Packing $PROJECT -> ${VERSION}";
          dotnet pack "$PROJECT" -c Release --no-build -p:PackageVersion=${VERSION} -p:ContinuousIntegrationBuild=true -o artifacts

      - name: Publish Packages (NuGet)
        if: success()
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/*.nupkg
          retention-days: 14
